services:
    bangpound_twitter_streaming.admin.location:
        class: Bangpound\Bundle\TwitterStreamingBundle\Admin\LocationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Twitter, label: Location }
        arguments:
            - ~
            - Bangpound\Bundle\TwitterStreamingBundle\Entity\Location
            - 'BangpoundTwitterStreamingBundle:CRUD'

    bangpound_twitter_streaming.admin.track:
        class: Bangpound\Bundle\TwitterStreamingBundle\Admin\TrackAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Twitter, label: Track }
        arguments:
            - ~
            - Bangpound\Bundle\TwitterStreamingBundle\Entity\Track
            - 'BangpoundTwitterStreamingBundle:CRUD'

    bangpound_twitter_streaming.admin.follow:
        class: Bangpound\Bundle\TwitterStreamingBundle\Admin\FollowAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Twitter, label: Follow }
        arguments:
            - ~
            - Bangpound\Bundle\TwitterStreamingBundle\Entity\Follow
            - 'BangpoundTwitterStreamingBundle:CRUD'
