services:
    bangpound_twitter_streaming.admin.location:
        class: Bangpound\Twitter\StreamingBundle\Admin\LocationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Filter, label: Location }
        arguments:
            - ~
            - Bangpound\Twitter\StreamingBundle\Entity\Location
            - 'SonataAdminBundle:CRUD'

    bangpound_twitter_streaming.admin.track:
        class: Bangpound\Twitter\StreamingBundle\Admin\TrackAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Filter, label: Track }
        arguments:
            - ~
            - Bangpound\Twitter\StreamingBundle\Entity\Track
            - 'SonataAdminBundle:CRUD'

    bangpound_twitter_streaming.admin.follow:
        class: Bangpound\Twitter\StreamingBundle\Admin\FollowAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Filter, label: Follow }
        arguments:
            - ~
            - Bangpound\Twitter\StreamingBundle\Entity\Follow
            - 'SonataAdminBundle:CRUD'
