parameters:
     bangpound_twitter_streaming.db.table_prefix: twitter_streaming__

services:
    bangpound_twitter_streaming.tblprefix_subscriber:
        class: Bangpound\Twitter\StreamingBundle\Subscriber\TablePrefixSubscriber
        arguments: [%bangpound_twitter_streaming.db.table_prefix%]
        tags:
            - { name: doctrine.event_subscriber }
